"""Business logic stubs for the Intelligence Service.

This module provides stub implementations for emergency classification
and guidance generation.  The real Gemini 1.5 Pro integration will be
added in tasks 4.2 and 4.6 respectively.

Requirements: 2.1, 2.7, 5.1
"""

from __future__ import annotations

from datetime import datetime, timezone

from shared.models import (
    CallerRole,
    CallerState,
    EmergencyClassification,
    EmergencyType,
    PanicLevel,
    Severity,
)


def classify_transcript(call_id: str, transcript: str) -> EmergencyClassification:
    """Produce an ``EmergencyClassification`` from a transcript.

    This is a **stub** that returns a default classification.  The real
    implementation (task 4.2) will call Gemini 1.5 Pro and stream
    partial JSON results to Firebase RTDB.
    """
    return EmergencyClassification(
        call_id=call_id,
        emergency_type=EmergencyType.UNKNOWN,
        severity=Severity.MODERATE,
        caller_state=CallerState(
            panic_level=PanicLevel.CALM,
            caller_role=CallerRole.BYSTANDER,
        ),
        language_detected="hi",
        key_facts=[],
        confidence=0.5,
        timestamp=datetime.now(timezone.utc),
        model_version="stub-v0",
    )


def generate_guidance(
    call_id: str,
    classification: EmergencyClassification,
    caller_state: CallerState,
) -> str:
    """Generate caller guidance text based on classification and caller state.

    This is a **stub** that returns placeholder guidance.  The real
    implementation (task 4.6) will use Gemini 1.5 Pro to produce
    adaptive, protocol-grounded guidance in the caller's language.

    Guidance is only generated for severity CRITICAL or HIGH
    (Requirement 5.1).
    """
    if classification.severity not in (Severity.CRITICAL, Severity.HIGH):
        return ""

    return (
        f"[Stub guidance for {classification.emergency_type.value} emergency, "
        f"severity {classification.severity.value}. "
        f"Caller state: {caller_state.panic_level.value}/{caller_state.caller_role.value}. "
        f"Language: {classification.language_detected}. "
        f"Real guidance will be generated by Gemini 1.5 Pro in task 4.6.]"
    )
